[book]
authors = ["Blaž Hrastnik", "zjp <jiping_zhou@foxmail.com>"]
language = "zh"
multilingual = false
src = "src"
title = "Helix Book 中文翻译"

[preprocessor.theme]
pagetoc = true
sidebar-width = "250px"

[output.html]
default-theme = "colibri"
preferred-dark-theme = "colibri"
git-repository-url = "https://github.com/zjp-CN/helix-book"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"
